#!/bin/sh

rm -rfv app/Books
rm -rfv app/CalculatorGoogle
rm -rfv app/CalendarGooglePrebuilt
rm -rfv app/Chrome
rm -rfv app/CloudPrint
rm -rfv app/CloudPrint2
rm -rfv app/ConfigUpdater
rm -rfv app/DMAgent
rm -rfv app/Drive
rm -rfv app/EditorsDocs
rm -rfv app/EditorsSheets
rm -rfv app/EditorsSlides
rm -rfv app/ExchangeServices
rm -rfv app/FaceLock
rm -rfv app/FitnessPrebuilt
rm -rfv app/GoogleCalendarSyncAdapter
rm -rfv app/GoogleCamera
rm -rfv app/GoogleContactsSyncAdapter
rm -rfv app/GoogleEars
rm -rfv app/GoogleEarth
rm -rfv app/GoogleHindiIME
rm -rfv app/GoogleHome
rm -rfv app/GoogleJapaneseInput
rm -rfv app/GooglePinyinIME
rm -rfv app/GoogleTTS
rm -rfv app/Hangouts
rm -rfv app/Duo
rm -rfv app/HangoutsDialer
rm -rfv app/KoreanIME
rm -rfv app/LatinImeGoogle
rm -rfv app/Maps
rm -rfv app/Music2
rm -rfv app/Newsstand
rm -rfv app/Photos
rm -rfv app/PlayAutoInstallConfig
rm -rfv app/PlayGames
rm -rfv app/PlusOne
rm -rfv app/PrebuiltBugle
rm -rfv app/PrebuiltDeskClockGoogle
rm -rfv app/PrebuiltEmailGoogle
rm -rfv app/PrebuiltExchange3Google
rm -rfv app/PrebuiltGmail
rm -rfv app/PrebuiltKeep
rm -rfv app/PrebuiltNewsWeather
rm -rfv app/PrintSpooler
rm -rfv app/Street
rm -rfv app/talkback
rm -rfv app/Tycho
rm -rfv app/Videos
rm -rfv app/Wallet
rm -rfv app/YouTube

rm -rfv priv-app/AndroidForWork
rm -rfv priv-app/BackupRestoreConfirmation
rm -rfv priv-app/CalendarProvider
rm -rfv priv-app/ConfigUpdater
rm -rfv priv-app/ConnMO
rm -rfv priv-app/GCS
rm -rfv priv-app/GoogleBackupTransport
rm -rfv priv-app/GoogleContacts
rm -rfv priv-app/GoogleDialer
rm -rfv priv-app/GoogleFeedback
rm -rfv priv-app/GoogleLoginService
rm -rfv priv-app/GoogleOneTimeInitializer
rm -rfv priv-app/GooglePackageInstaller
rm -rfv priv-app/GooglePartnerSetup
rm -rfv priv-app/GoogleServicesFramework
rm -rfv priv-app/Hangouts
rm -rfv priv-app/HotwordEnrollment
rm -rfv priv-app/Phonesky
rm -rfv priv-app/PrebuiltGmsCore
rm -rfv priv-app/SetupWizard
rm -rfv priv-app/TagGoogle
rm -rfv priv-app/Talkback
rm -rfv priv-app/Velvet
rm -rfv priv-app/Wallet

rm -rfv tts
rm -rfv usr/srec
rm -rfv vendor/pittpatt

rm -fv addon.d/70-gapps.sh
rm -fv addon.d/71-faceunlock.sh
rm -fv addon.d/71-gapps-faceunlock.sh
rm -fv addon.d/74-googlecamera.sh
rm -fv addon.d/74-googlegallery.sh
rm -fv addon.d/75-googlegallery.sh
rm -fv addon.d/78-chromebrowser.sh

rm -fv app/Books.apk
rm -fv app/Books.odex
rm -fv app/BooksPhone.apk
rm -fv app/BooksPhone.odex
rm -fv app/BrowserProviderProxy.apk
rm -fv app/BrowserProviderProxy.odex
rm -fv app/CalculatorGoogle.apk
rm -fv app/CalculatorGoogle.odex
rm -fv app/Calendar.apk
rm -fv app/Duo.apk
rm -fv app/Calendar.odex
rm -fv app/CalendarGoogle.apk
rm -fv app/CalendarGoogle.odex
rm -fv app/CalendarGooglePrebuilt.apk
rm -fv app/CalendarGooglePrebuilt.odex
rm -fv app/CalendarProvider.apk
rm -fv app/CalendarProvider.odex
rm -fv app/CarHomeGoogle.apk
rm -fv app/CarHomeGoogle.odex
rm -fv app/CellBroadcastReceiver.apk
rm -fv app/CellBroadcastReceiver.odex
rm -fv app/Chrome.apk
rm -fv app/Chrome.odex
rm -fv app/ChromeBookmarksSyncAdapter.apk
rm -fv app/ChromeBookmarksSyncAdapter.odex
rm -fv app/CloudPrint.apk
rm -fv app/CloudPrint.odex
rm -fv app/CloudPrint2.apk
rm -fv app/CloudPrint2.odex
rm -fv app/ConfigUpdater.apk
rm -fv app/ConfigUpdater.odex
rm -fv app/Currents.apk
rm -fv app/Currents.odex
rm -fv app/DeskClockGoogle.apk
rm -fv app/DeskClockGoogle.odex
rm -fv app/DMAgent.apk
rm -fv app/DMAgent.odex
rm -fv app/Drive.apk
rm -fv app/Drive.odex
rm -fv app/EditorsDocs.apk
rm -fv app/EditorsDocs.odex
rm -fv app/EditorsSheets.apk
rm -fv app/EditorsSheets.odex
rm -fv app/EditorsSlides.apk
rm -fv app/EditorsSlides.odex
rm -fv app/ExchangeServices.apk
rm -fv app/ExchangeServices.odex
rm -fv app/FaceLock.apk
rm -fv app/FaceLock.odex
rm -fv app/Finsky.apk
rm -fv app/Finsky.odex
rm -fv app/FitnessPrebuilt.apk
rm -fv app/FitnessPrebuilt.odex
rm -fv app/FOTAKill.apk
rm -fv app/FOTAKill.odex
rm -fv app/GalleryGoogle.apk
rm -fv app/GalleryGoogle.odex
rm -fv app/GenieWidget.apk
rm -fv app/GenieWidget.odex
rm -fv app/Gmail.apk
rm -fv app/Gmail.odex
rm -fv app/Gmail2.apk
rm -fv app/Gmail2.odex
rm -fv app/GmsCore.apk
rm -fv app/GmsCore.odex
rm -fv app/GoogleBackupTransport.apk
rm -fv app/GoogleBackupTransport.odex
rm -fv app/GoogleCalendar.apk
rm -fv app/GoogleCalendar.odex
rm -fv app/GoogleCalendarSyncAdapter.apk
rm -fv app/GoogleCalendarSyncAdapter.odex
rm -fv app/GoogleCamera.apk
rm -fv app/GoogleCamera.odex
rm -fv app/GoogleCloudPrint.apk
rm -fv app/GoogleCloudPrint.odex
rm -fv app/GoogleContactsSyncAdapter.apk
rm -fv app/GoogleContactsSyncAdapter.odex
rm -fv app/GoogleEars.apk
rm -fv app/GoogleEars.odex
rm -fv app/GoogleEarth.apk
rm -fv app/GoogleEarth.odex
rm -fv app/GoogleFeedback.apk
rm -fv app/GoogleFeedback.odex
rm -fv app/GoogleHangouts.apk
rm -fv app/GoogleHangouts.odex
rm -fv app/GoogleHindiIME.apk
rm -fv app/GoogleHindiIME.odex
rm -fv app/GoogleHome.apk
rm -fv app/GoogleHome.odex
rm -fv app/GoogleJapaneseInput.apk
rm -fv app/GoogleJapaneseInput.odex
rm -fv app/GoogleKeep.apk
rm -fv app/GoogleKeep.odex
rm -fv app/GoogleLatinIme.apk
rm -fv app/GoogleLatinIme.odex
rm -fv app/GoogleLoginService.apk
rm -fv app/GoogleLoginService.odex
rm -fv app/GoogleMusic.apk
rm -fv app/GoogleMusic.odex
rm -fv app/GoogleNow.apk
rm -fv app/GoogleNow.odex
rm -fv app/GoogleOneTimeInitializer.apk
rm -fv app/GoogleOneTimeInitializer.odex
rm -fv app/GooglePartnerSetup.apk
rm -fv app/GooglePartnerSetup.odex
rm -fv app/GooglePinyinIME.apk
rm -fv app/GooglePinyinIME.odex
rm -fv app/GooglePlay.apk
rm -fv app/GooglePlay.odex
rm -fv app/GooglePlus.apk
rm -fv app/GooglePlus.odex
rm -fv app/GoogleQuickSearchBox.apk
rm -fv app/GoogleQuickSearchBox.odex
rm -fv app/GoogleServicesFramework.apk
rm -fv app/GoogleServicesFramework.odex
rm -fv app/GoogleTTS.apk
rm -fv app/GoogleTTS.odex
rm -fv app/Hangouts.apk
rm -fv app/Hangouts.odex
rm -fv app/HangoutsDialer.apk
rm -fv app/HangoutsDialer.odex
rm -fv app/iWnnIME.apk
rm -fv app/iWnnIME.odex
rm -fv app/iWnnIME_Kbd_White.apk
rm -fv app/iWnnIME_Kbd_White.odex
rm -fv app/Keep.apk
rm -fv app/Keep.odex
rm -fv app/KoreanIME.apk
rm -fv app/KoreanIME.odex
rm -fv app/LatinIME.apk
rm -fv app/LatinIME.odex
rm -fv app/LatinImeDictionaryPack.apk
rm -fv app/LatinImeDictionaryPack.odex
rm -fv app/LatinImeGoogle.apk
rm -fv app/LatinImeGoogle.odex
rm -fv app/LatinImeTutorial.apk
rm -fv app/LatinImeTutorial.odex
rm -fv app/Magazines.apk
rm -fv app/Magazines.odex
rm -fv app/Maps.apk
rm -fv app/Maps.odex
rm -fv app/MarketUpdater.apk
rm -fv app/MarketUpdater.odex
rm -fv app/MediaUploader.apk
rm -fv app/MediaUploader.odex
rm -fv app/Music2.apk
rm -fv app/Music2.odex
rm -fv app/NetworkLocation.apk
rm -fv app/NetworkLocation.odex
rm -fv app/Newsstand.apk
rm -fv app/Newsstand.odex
rm -fv app/OccamQuickOffice.apk
rm -fv app/OccamQuickOffice.odex
rm -fv app/OneTimeInitializer.apk
rm -fv app/OneTimeInitializer.odex
rm -fv app/PartnerBookmarksProvider.apk
rm -fv app/PartnerBookmarksProvider.odex
rm -fv app/Phonesky.apk
rm -fv app/Phonesky.odex
rm -fv app/Photos.apk
rm -fv app/Photos.odex
rm -fv app/PlayAutoInstallConfig.apk
rm -fv app/PlayAutoInstallConfig.odex
rm -fv app/PlayGames.apk
rm -fv app/PlayGames.odex
rm -fv app/PlayStore.apk
rm -fv app/PlayStore.odex
rm -fv app/PlusOne.apk
rm -fv app/PlusOne.odex
rm -fv app/PrebuiltBugle.apk
rm -fv app/PrebuiltBugle.odex
rm -fv app/PrebuiltDeskClockGoogle.apk
rm -fv app/PrebuiltDeskClockGoogle.odex
rm -fv app/PrebuiltEmailGoogle.apk
rm -fv app/PrebuiltEmailGoogle.odex
rm -fv app/PrebuiltExchange3Google.apk
rm -fv app/PrebuiltExchange3Google.odex
rm -fv app/PrebuiltGmail.apk
rm -fv app/PrebuiltGmail.odex
rm -fv app/PrebuiltGmsCore.apk
rm -fv app/PrebuiltGmsCore.odex
rm -fv app/PrebuiltKeep.apk
rm -fv app/PrebuiltKeep.odex
rm -fv app/PrebuiltNewsWeather.apk
rm -fv app/PrebuiltNewsWeather.odex
rm -fv app/PrintSpooler.apk
rm -fv app/PrintSpooler.odex
rm -fv app/QuickOffice.apk
rm -fv app/QuickOffice.odex
rm -fv app/QuickSearchBox.apk
rm -fv app/QuickSearchBox.odex
rm -fv app/SetupWizard.apk
rm -fv app/SetupWizard.odex
rm -fv app/Street.apk
rm -fv app/Street.odex
rm -fv app/Talk.apk
rm -fv app/Talk.odex
rm -fv app/Tycho.apk
rm -fv app/Tycho.odex
rm -fv app/Velvet.apk
rm -fv app/Velvet.odex
rm -fv app/Vending.apk
rm -fv app/Vending.odex
rm -fv app/Videos.apk
rm -fv app/Videos.odex
rm -fv app/Wallet.apk
rm -fv app/Wallet.odex
rm -fv app/YouTube.apk
rm -fv app/YouTube.odex

rm -fv priv-app/AndroidForWork.apk
rm -fv priv-app/AndroidForWork.odex
rm -fv priv-app/BackupRestoreConfirmation.apk
rm -fv priv-app/BackupRestoreConfirmation.odex
rm -fv priv-app/Books.apk
rm -fv priv-app/Books.odex
rm -fv priv-app/Calendar.apk
rm -fv priv-app/Calendar.odex
rm -fv priv-app/CalendarGooglePrebuilt.apk
rm -fv priv-app/CalendarGooglePrebuilt.odex
rm -fv priv-app/CalendarProvider.apk
rm -fv priv-app/CalendarProvider.odex
rm -fv priv-app/Chrome.apk
rm -fv priv-app/Chrome.odex
rm -fv priv-app/CloudPrint2.apk
rm -fv priv-app/CloudPrint2.odex
rm -fv priv-app/ConfigUpdater.apk
rm -fv priv-app/ConfigUpdater.odex
rm -fv priv-app/ConnMO.apk
rm -fv priv-app/ConnMO.odex
rm -fv priv-app/DMAgent.apk
rm -fv priv-app/DMAgent.odex
rm -fv priv-app/Drive.apk
rm -fv priv-app/Drive.odex
rm -fv priv-app/EditorsDocs.apk
rm -fv priv-app/EditorsDocs.odex
rm -fv priv-app/EditorsSheets.apk
rm -fv priv-app/EditorsSheets.odex
rm -fv priv-app/EditorsSlides.apk
rm -fv priv-app/EditorsSlides.odex
rm -fv priv-app/FaceLock.apk
rm -fv priv-app/FaceLock.odex
rm -fv priv-app/FitnessPrebuilt.apk
rm -fv priv-app/FitnessPrebuilt.odex
rm -fv priv-app/GCS.apk
rm -fv priv-app/GCS.odex
rm -fv priv-app/GmsCore.apk
rm -fv priv-app/GmsCore.odex
rm -fv priv-app/GoogleBackupTransport.apk
rm -fv priv-app/GoogleBackupTransport.odex
rm -fv priv-app/GoogleCalendarSyncAdapter.apk
rm -fv priv-app/GoogleCalendarSyncAdapter.odex
rm -fv priv-app/GoogleCamera.apk
rm -fv priv-app/GoogleCamera.odex
rm -fv priv-app/GoogleContacts.apk
rm -fv priv-app/GoogleContacts.odex
rm -fv priv-app/GoogleContactsSyncAdapter.apk
rm -fv priv-app/GoogleContactsSyncAdapter.odex
rm -fv priv-app/GoogleDialer.apk
rm -fv priv-app/GoogleDialer.odex
rm -fv priv-app/GoogleEars.apk
rm -fv priv-app/GoogleEars.odex
rm -fv priv-app/GoogleEarth.apk
rm -fv priv-app/GoogleEarth.odex
rm -fv priv-app/GoogleFeedback.apk
rm -fv priv-app/GoogleFeedback.odex
rm -fv priv-app/GoogleHindiIME.apk
rm -fv priv-app/GoogleHindiIME.odex
rm -fv priv-app/GoogleHome.apk
rm -fv priv-app/GoogleHome.odex
rm -fv priv-app/GoogleJapaneseInput.apk
rm -fv priv-app/GoogleJapaneseInput.odex
rm -fv priv-app/GoogleLoginService.apk
rm -fv priv-app/GoogleLoginService.odex
rm -fv priv-app/GoogleNow.apk
rm -fv priv-app/GoogleNow.odex
rm -fv priv-app/GoogleOneTimeInitializer.apk
rm -fv priv-app/GoogleOneTimeInitializer.odex
rm -fv priv-app/GooglePackageInstaller.apk
rm -fv priv-app/GooglePackageInstaller.odex
rm -fv priv-app/GooglePartnerSetup.apk
rm -fv priv-app/GooglePartnerSetup.odex
rm -fv priv-app/GooglePinyinIME.apk
rm -fv priv-app/GooglePinyinIME.odex
rm -fv priv-app/GoogleServicesFramework.apk
rm -fv priv-app/GoogleServicesFramework.odex
rm -fv priv-app/Hangouts.apk
rm -fv priv-app/Hangouts.odex
rm -fv priv-app/HotwordEnrollment.apk
rm -fv priv-app/HotwordEnrollment.odex
rm -fv priv-app/KoreanIME.apk
rm -fv priv-app/KoreanIME.odex
rm -fv priv-app/LatinImeGoogle.apk
rm -fv priv-app/LatinImeGoogle.odex
rm -fv priv-app/Maps.apk
rm -fv priv-app/Maps.odex
rm -fv priv-app/Music2.apk
rm -fv priv-app/Music2.odex
rm -fv priv-app/Newsstand.apk
rm -fv priv-app/Newsstand.odex
rm -fv priv-app/OneTimeInitializer.apk
rm -fv priv-app/OneTimeInitializer.odex
rm -fv priv-app/Phonesky.apk
rm -fv priv-app/Phonesky.odex
rm -fv priv-app/Photos.apk
rm -fv priv-app/Photos.odex
rm -fv priv-app/PlayAutoInstallConfig.apk
rm -fv priv-app/PlayAutoInstallConfig.odex
rm -fv priv-app/PlayGames.apk
rm -fv priv-app/PlayGames.odex
rm -fv priv-app/PlusOne.apk
rm -fv priv-app/PlusOne.odex
rm -fv priv-app/PrebuiltBugle.apk
rm -fv priv-app/PrebuiltBugle.odex
rm -fv priv-app/PrebuiltEmailGoogle.apk
rm -fv priv-app/PrebuiltEmailGoogle.odex
rm -fv priv-app/PrebuiltExchange3Google.apk
rm -fv priv-app/PrebuiltExchange3Google.odex
rm -fv priv-app/PrebuiltGmail.apk
rm -fv priv-app/PrebuiltGmail.odex
rm -fv priv-app/PrebuiltGmsCore.apk
rm -fv priv-app/PrebuiltGmsCore.odex
rm -fv priv-app/PrebuiltKeep.apk
rm -fv priv-app/PrebuiltKeep.odex
rm -fv priv-app/PrebuiltNewsWeather.apk
rm -fv priv-app/PrebuiltNewsWeather.odex
rm -fv priv-app/QuickSearchBox.apk
rm -fv priv-app/QuickSearchBox.odex
rm -fv priv-app/SetupWizard.apk
rm -fv priv-app/SetupWizard.odex
rm -fv priv-app/Street.apk
rm -fv priv-app/Street.odex
rm -fv priv-app/TagGoogle.apk
rm -fv priv-app/TagGoogle.odex
rm -fv priv-app/Talkback.apk
rm -fv priv-app/Talkback.odex
rm -fv priv-app/Velvet.apk
rm -fv priv-app/Velvet.odex
rm -fv priv-app/Vending.apk
rm -fv priv-app/Vending.odex
rm -fv priv-app/Videos.apk
rm -fv priv-app/Videos.odex
rm -fv priv-app/Wallet.apk
rm -fv priv-app/Wallet.odex
rm -fv priv-app/YouTube.apk
rm -fv priv-app/YouTube.odex

rm -fv vendor/lib/libfrsdk.so
